car/urls.py
from django.urls import path

from . import views

app_name = 'car'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('list/', views.ListCars.as_view(), name='list'),
    path('details/<int:pk>', views.CarDetailView.as_view(), name='detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultView.as_view(), name='search_result'),
    path('rent/<int:pk>/', views.rent_car, name='rent'),
    path('checkout/<int:rental_id>/', views.checkout, name='checkout'),
    path('complete_order/', views.complete_order, name='complete'),
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("car.urls")),
    path('', include('user.urls'))
]

user/urls.py
from . import views

from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('', views.UserLoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile_view, name="profile"),
    path('return/<int:pk>', views.return_car, name='return')
]
 

templates/checkout.html
{% extends 'home.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'checkout_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <div class="container mt-4">
        <a class="btn btn-primary m-3" href="{% url 'car:rent' rental.car.id %}">Back</a>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img class="custom-image" src="{{rental.car.image_url}}" alt="{{rental.car.model}}">
                    <div class="card-body">
                        <h1>{{ rental.car.make }}</h1>
                        <h3>{{ rental.car.model }}</h3>
                        <p>Price per day: {{ rental.car.price }}</p>
                        <p>Rental date: {{ rental.rental_date }}</p>
                        <p>Return date: {{ rental.return_date }}</p>
                    </div>
                </div>       
            </div>

            <div class="col-md-6 text-center mx-auto my-auto">
                <h1>Payment</h1>
                <h3>Total Price: {{ rental.rental_amount }}</h3>
                <!--Paypal payments-->
                
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>
    
    <script 
    src="https://www.paypal.com/sdk/js?client-id=AfTaY8RgJC4rNnsJdeg2uJNK2esNMT27dLk64zDK3K9adJEp0RYSx0nnWU2Kk5MkvCBcg6yfdg6uxCDf&currency=USD">
    </script>

    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        var total = '{{object.rental_amount}}'
        var rental_id = '{{rental.id}}'

        function completeOrder() {
            var url = "{% url 'car:complete' %}";
        
            fetch(url, {
                method: 'POST',
                headers: {
                    'content-type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({ 'rental_id': rental_id })
            })
            .then(response => response.json())
            .then(data => {
                // Handle the response data as needed
            })
            .catch(error => {
                console.error('Error:', error);
            });

            setTimeout(function() {
                window.location.href = "{% url 'car:list' %}";
            }, 500);
        }
        
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{ rental.rental_amount }}'
                        }
                    }]
                });
            },
            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    // Show a success message to the buyer
                    completeOrder();
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }
        }).render('#paypal-button-container');
    </script>
</body>
</html>

{% endblock content %}

templates/detail.html
{% extends 'home.html' %}
{% block content %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'detail_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <h1 class="text-center">Car Details</h1>
    <div class="container p-4 mt-3">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img class="custom-image" src="{{object.image_url}}" alt="{{object.model}}">
                </div>
            </div>
            <div class="col-md-4">
                <div class="box">
                    <h1>{{object.make}}</h1>
                    <p>{{object.model}}</p>
                    <p>{{object.year}}</p>
                    {% if object.availability is True %}
                    <p class="text-success">Available</p>
                    {% else %}
                    <p class="text-danger">Not available</p>
                    {% endif %}
                    <p class="text-success"><strong>{{object.fuel}}</strong></p>
                    <p>Location: {{ object.location }}</p>
                    <a class="btn btn-primary" href="{% url 'car:list' %}">Back</a>
                    <a class="btn btn-success" href="{% url 'car:rent' object.id %}">Rent this car</a>
                </div>
            </div>
        </div> 
    </div>
</body>
</html>
{% endblock content %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
    <link rel="stylesheet" href="{% static 'home_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><strong>Car Rent</strong></a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'car:list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact us</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i>
              {{user}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'user:login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'user:signup' %}">Register</a></li>
              {% endif %}   
            </ul>
          </li>
        </ul>
        <a class="btn btn-success" href="{% url 'car:search' %}">Find Car</a>
      </div>
    </div>
  </nav>
  
  <div class="">
    {% block content %}

    {% endblock content %}
  </div>

  <div class="container-fluid bg-dark div-light mt-5">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-2 border-top">
      <p class="col-md-4 mb-0 text-muted">© 2022 Company, Inc</p>
  
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-light text-decoration-none">
        <h4><strong>Car Rent</strong></h4>
      </a>
  
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
    </footer>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/list.html
{% extends 'home.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'list_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <div class="container mt-4">
        <class class="row g-4">
            {% for car in cars %}
            <div class="col-md-3 col-sm-6">
                <div class="card custom-card">
                    <img class="card-img-top custom-card-image" src="{{car.image_url}}" alt="{{car.make}}">
                    <div class="card-body">
                        <h3>{{car.make}}</h3>
                        <h3>{{car.model}}</h3>
                        <a class="btn btn-primary" href="{% url 'car:detail' car.id %}">View</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </class>
    </div>
</body>
</html>
{% endblock content %}

templates/profile.html
{% extends 'home.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Profile</title>
</head>
<body>
    <div class="container border mx-3 my-3">
        <h1>Your Profile</h1>
        <p>Username: {{user.username}}</p>
        <p>Email: {{user.email}}</p>
        <hr>

        <h1>Your Rentals</h1>
        <!-- List current rented cars -->
        <h4>Current Rented Cars</h4>
        {% for rental in current_rentals %}
            <p>{{ rental.car.make }} - {{ rental.car.model }}</p>
            <p>Rental duration: {{ rental.rental_date }} to {{ rental.return_date }}</p>
            {{rental.car.pk}}
            <a class="btn btn-danger" href="{% url 'user:return' rental.pk %}">Return</a>
        {% empty %}
            <p>No current rented cars.</p>
        {% endfor %}

        <!-- List past rented cars -->
        <h4>Past Rented Cars</h4>
        {% for rental in past_rentals %}
            <p>Car: {{ rental.car.make }} - {{ rental.car.model }}</p>
            <p>Rental duration: {{ rental.rental_date }} to {{ rental.return_date }}</p>
        {% empty %}
            <p>No past rented cars.</p>
        {% endfor %}
    </div>
</body>
</html>

{% endblock content %}

templates/rental_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'rental_form_style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Rental Date</title>
</head>
<body>
    <form method="post">
        <h1>Pick Days</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Rent</button>
    </form> 
</body>
</html>

templates/search.html
{% extends 'home.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'search_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <div class="card border-0">
            <form action="{% url 'car:search_result' %}" method="get">
                <h2>Find a car for you</h2>
                <input type="text" name="make" id="" placeholder="Enter car make"><br>
                <input type="text" name="model" id="" placeholder="Enter car model"><br>
                <input type="number" name="price" id="" placeholder="Enter maximum rental price"><br>
                <input type="text" name="location" id="" placeholder="Enter pickup location"><br>
                <input type="text" name="fuel" id="" placeholder="Enter fuel type"><br>
                <button class="btn btn-success" type="submit">Search</button>
            </form>
            <a class="btn btn-danger mt-3" href="{% url 'car:list' %}">Back</a>
        </div>
    </div>
</body>
</html>
{% endblock content %}

templates/search_result.html
{% extends 'home.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'search_result_style.css' %}" rel="stylesheet"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            {% if cars %}
            {% for car in cars %}
            <div class="col-md-3 clo-sm-6">
                <div class="card custom-card">
                    <img class="card-img-top custom-card-image" src="{{car.image_url}}" alt="{{car.make}}">
                    <div class="card-body">
                        <h3>{{car.make}}</h3>
                        <h3>{{car.model}}</h3>
                        <a class="btn btn-primary" href="{% url 'car:detail' car.id %}">View</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% else %}
                <h3>{{empty_message}}</h3>
            {% endif %}
        </div>
    </div>
</body>
</html>
{% endblock content %}

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'signup_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
      <h1>Signup</h1>
      {% csrf_token %}
      {{form.as_p }}
      <button class="btn btn-primary" type="submit">Signup</button>
      <p>Already have an account? <a href="{% url 'user:login' %}">Login</a></p>
    </form>
</body>
</html>